name: Terraform Check

on:
  pull_request:
    branches:
      - main
      - dev
      - stg

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, stg, prd]
    defaults:
        run:
            working-directory: terraform/environments/${{ matrix.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.5

      - name: Terraform init
        run: terraform init"

      - name: Terraform validate
        run: terraform validate 

      - name: Terraform lint
        run: terraform fmt -check

      - name: Terraform test
        run: terraform test

      - name: Terraform plan
        run: terraform plan
