name: Terraform Validation

on:
    workflow_dispatch:
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.3.0'


    - name: Terraform Init
      run: terraform init"
      working-directory: terraform/environments/prd
    
    - name: Terraform apply
      run: terraform apply -auto-approve
